CREATE DATABASE IF NOT EXISTS STOCK_STREAMING;
CREATE SCHEMA IF NOT EXISTS STOCK_STREAMING.MARKET;

CREATE WAREHOUSE IF NOT EXISTS STREAMING_WH
  WAREHOUSE_SIZE = XSMALL
  AUTO_SUSPEND = 60
  AUTO_RESUME = TRUE
  INITIALLY_SUSPENDED = TRUE;

USE DATABASE STOCK_STREAMING;
USE SCHEMA MARKET;
USE WAREHOUSE STREAMING_WH;

CREATE TABLE IF NOT EXISTS BRONZE_KAFKA_TRADES (
  RECORD_CONTENT VARIANT,
  RECORD_METADATA VARIANT,
  KAFKA_RECEIVED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE TABLE IF NOT EXISTS BRONZE_TRADE_DLQ (
  RECORD_CONTENT VARIANT,
  RECORD_METADATA VARIANT,
  ERROR_REASON STRING,
  KAFKA_RECEIVED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE TABLE IF NOT EXISTS SILVER_VALID_TRADES (
  TRADE_ID STRING,
  SYMBOL STRING,
  SIDE STRING,
  QUANTITY NUMBER,
  PRICE NUMBER(18, 4),
  NOTIONAL NUMBER(18, 4),
  EVENT_TS TIMESTAMP_TZ,
  INGEST_TS TIMESTAMP_TZ,
  EXCHANGE STRING,
  TRADER_ID STRING,
  SEQUENCE NUMBER,
  SOURCE_OFFSET NUMBER,
  LOADED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE TABLE IF NOT EXISTS GOLD_TRADE_ANOMALIES (
  TRADE_ID STRING,
  SYMBOL STRING,
  SIDE STRING,
  QUANTITY NUMBER,
  PRICE NUMBER(18, 4),
  NOTIONAL NUMBER(18, 4),
  EVENT_TS TIMESTAMP_TZ,
  ANOMALY_REASON STRING,
  SEVERITY STRING,
  LOADED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE TABLE IF NOT EXISTS GOLD_SYMBOL_WINDOWS_1M (
  WINDOW_START TIMESTAMP_TZ,
  WINDOW_END TIMESTAMP_TZ,
  SYMBOL STRING,
  TRADE_COUNT NUMBER,
  TOTAL_QUANTITY NUMBER,
  TOTAL_NOTIONAL NUMBER(18, 4),
  VWAP NUMBER(18, 4),
  LOADED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

