USE DATABASE STOCK_STREAMING;
USE SCHEMA MARKET;
USE WAREHOUSE STREAMING_WH;

CREATE STREAM IF NOT EXISTS BRONZE_KAFKA_TRADES_STREAM
  ON TABLE BRONZE_KAFKA_TRADES
  APPEND_ONLY = TRUE;

CREATE OR REPLACE TASK TASK_BRONZE_TO_SILVER
  WAREHOUSE = STREAMING_WH
  SCHEDULE = '1 MINUTE'
  WHEN SYSTEM$STREAM_HAS_DATA('BRONZE_KAFKA_TRADES_STREAM')
AS
MERGE INTO SILVER_VALID_TRADES target
USING (
  SELECT
    RECORD_CONTENT:trade_id::STRING AS TRADE_ID,
    UPPER(RECORD_CONTENT:symbol::STRING) AS SYMBOL,
    RECORD_CONTENT:side::STRING AS SIDE,
    RECORD_CONTENT:quantity::NUMBER AS QUANTITY,
    RECORD_CONTENT:price::NUMBER(18, 4) AS PRICE,
    RECORD_CONTENT:quantity::NUMBER * RECORD_CONTENT:price::NUMBER(18, 4) AS NOTIONAL,
    TRY_TO_TIMESTAMP_TZ(RECORD_CONTENT:event_time::STRING) AS EVENT_TS,
    TRY_TO_TIMESTAMP_TZ(RECORD_CONTENT:ingest_time::STRING) AS INGEST_TS,
    RECORD_CONTENT:exchange::STRING AS EXCHANGE,
    RECORD_CONTENT:trader_id::STRING AS TRADER_ID,
    RECORD_CONTENT:sequence::NUMBER AS SEQUENCE,
    RECORD_METADATA:offset::NUMBER AS SOURCE_OFFSET
  FROM BRONZE_KAFKA_TRADES_STREAM
  WHERE RECORD_CONTENT:trade_id IS NOT NULL
    AND RECORD_CONTENT:symbol IS NOT NULL
    AND RECORD_CONTENT:side::STRING IN ('BUY', 'SELL')
    AND RECORD_CONTENT:quantity::NUMBER > 0
    AND RECORD_CONTENT:price::NUMBER > 0
    AND TRY_TO_TIMESTAMP_TZ(RECORD_CONTENT:event_time::STRING) IS NOT NULL
) source
ON target.TRADE_ID = source.TRADE_ID
WHEN NOT MATCHED THEN INSERT (
  TRADE_ID,
  SYMBOL,
  SIDE,
  QUANTITY,
  PRICE,
  NOTIONAL,
  EVENT_TS,
  INGEST_TS,
  EXCHANGE,
  TRADER_ID,
  SEQUENCE,
  SOURCE_OFFSET
) VALUES (
  source.TRADE_ID,
  source.SYMBOL,
  source.SIDE,
  source.QUANTITY,
  source.PRICE,
  source.NOTIONAL,
  source.EVENT_TS,
  source.INGEST_TS,
  source.EXCHANGE,
  source.TRADER_ID,
  source.SEQUENCE,
  source.SOURCE_OFFSET
);

CREATE OR REPLACE TASK TASK_SILVER_TO_GOLD_1M
  WAREHOUSE = STREAMING_WH
  AFTER TASK_BRONZE_TO_SILVER
AS
MERGE INTO GOLD_SYMBOL_WINDOWS_1M target
USING (
  SELECT
    DATE_TRUNC('MINUTE', EVENT_TS) AS WINDOW_START,
    DATEADD('MINUTE', 1, DATE_TRUNC('MINUTE', EVENT_TS)) AS WINDOW_END,
    SYMBOL,
    COUNT(*) AS TRADE_COUNT,
    SUM(QUANTITY) AS TOTAL_QUANTITY,
    SUM(NOTIONAL) AS TOTAL_NOTIONAL,
    SUM(NOTIONAL) / NULLIF(SUM(QUANTITY), 0) AS VWAP
  FROM SILVER_VALID_TRADES
  WHERE EVENT_TS >= DATEADD('HOUR', -2, CURRENT_TIMESTAMP())
  GROUP BY 1, 2, 3
) source
ON target.WINDOW_START = source.WINDOW_START
  AND target.SYMBOL = source.SYMBOL
WHEN MATCHED THEN UPDATE SET
  TRADE_COUNT = source.TRADE_COUNT,
  TOTAL_QUANTITY = source.TOTAL_QUANTITY,
  TOTAL_NOTIONAL = source.TOTAL_NOTIONAL,
  VWAP = source.VWAP,
  LOADED_AT = CURRENT_TIMESTAMP()
WHEN NOT MATCHED THEN INSERT (
  WINDOW_START,
  WINDOW_END,
  SYMBOL,
  TRADE_COUNT,
  TOTAL_QUANTITY,
  TOTAL_NOTIONAL,
  VWAP
) VALUES (
  source.WINDOW_START,
  source.WINDOW_END,
  source.SYMBOL,
  source.TRADE_COUNT,
  source.TOTAL_QUANTITY,
  source.TOTAL_NOTIONAL,
  source.VWAP
);

ALTER TASK TASK_BRONZE_TO_SILVER RESUME;
ALTER TASK TASK_SILVER_TO_GOLD_1M RESUME;

